### ISSUE TITLE
テストコードがないです...

### ISSUE THREAD

**Issue by eRy-sk** [ysk1180/rainnotice#1]
初めまして、LINEbot気になってたので購入させてもらいました。
早速なんですけれど、記事にテストコード書き忘れてないですか？
オリジナル要素を加える時にテストを加えて検証を行いたいので元のテストコードも記載お願いします！

**Comment by ysk1180** [comment]
@eRy-sk コメントありがとうございます！

大変申し訳無いのですが、こちらテストコードを書いておりません…
ご理解いただきますようお願いいたします……😭

**Comment by eRy-sk** [comment]
それだと応用ができないんですが...

**Comment by ysk1180** [comment]
@eRy-sk 大変恐縮ながらご自身でご対応いただけますと幸甚です。

**Comment by eRy-sk** [comment]
う〜ん、わかりました。
