### ISSUE TITLE
clientメソッドについて

### ISSUE THREAD

**Issue by eRy-sk** [ysk1180/rainnotice#2]
連投すみません、どうしても気になったので...
```ruby
  # app/controllers/line_bot_controller.rb
  def client
      @client ||= Line::Bot::Client.new { |config|
        config.channel_secret = ENV["LINE_CHANNEL_SECRET"]
        config.channel_token = ENV["LINE_CHANNEL_TOKEN"]
      }
    end
```
まず、ファイル名の命名が間違っています。
複数形にする必要があるのでそこの訂正はお願いします。

あとclientアクション(そもそもアクションではなさそう、メソッド？)は見えるところに晒してて平気なんでしょうか...？
僕は勝手にprivate下に置きましたけど...どうなんでしょう...？

**Comment by ysk1180** [comment]
@eRy-sk コメントありがとうございます！

①ファイル名の命名に関してですが、今回のline_botコントローラはモデルを扱わない為、単数形で問題は無いという認識です。
> モデルを扱うコントローラの場合はこの形式にしておいた方がいいですが、そうではないコントローラの場合は名前を常に複数形のように付ける必要はありません。
[コントローラの作成と命名規則(命名規約)](https://www.rubylife.jp/rails/controller/index1.html#section2)

気になるようでしたらご自身で複数形へ変更いただけますと幸甚です。

②clientメソッドについてはおっしゃる通りでございます。早急に変更致します。

他にも気になる点あればお気軽にコメントください😃

**Comment by eRy-sk** [comment]
確かにモデルを扱わないのであれば単数形でも可能ではありますけど、統一性だったりレールに乗せた書き方であったり、記事がチュートリアルであり、このプロジェクトの応用を推奨されてるみたいに受け取れたので、あとでモデルを追加するような"応用"がされても大丈夫なようにしとくべきかな...と思っての進言でした。失礼しました。
僕はメッセージをモデルから引っ張り出して送信するようにしたいと思っているので複数形にしておきます。
